apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-templates
data:
  template.app-sync-succeeded: |
    email:
      subject: Application {{.app.metadata.name}} has been successfully synced.
    message: |
      Application {{.app.metadata.name}} has been successfully synced.
      Sync operation details are available at: {{.context.argocdUrl}}/applications/{{.app.metadata.name}}?operation=true .
