apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-triggers
data:
  trigger.app-sync-succeeded: |
    - description: Application syncing has succeeded
      send:
      - app-sync-succeeded
      when: app.status.operationState.phase in ['Succeeded']
